platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5.4'              #网络请求

#platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'                   #图片缓存
#
pod 'MJRefresh' , '~> 2.3.2'                #下拉刷新
#
pod 'MBProgressHUD', '~> 0.9.1'             #加载提示
#
pod 'FMDB' , '~> 2.5'  #数据库
## pod 'FMDB/FTS'   # FMDB with FTS
## pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
## pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
## pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
#
#pod 'QBImagePickerController', '~> 2.5.2'   #相册
#
#pod 'EaseMobSDK', '~> 2.1.9'                #环信聊天
#
#pod 'JSONModel', '~> 1.1.0'                 #model格式化
#
pod 'MJExtension', '~> 2.5.5'               #model格式化
#
#pod 'jastor', '~> 0.2.1'                    #model格式化
#
#pod 'pop', '~> 1.0'                         #pop动画
#
#pod 'OBShapedButton'                        #不规则按钮
#
#pod 'FBGlowLabel', '~> 0.0.1'               #外发光
#
#pod 'MarqueeLabel', '~> 2.2.5'              #滚栋文本

#pod 'CorePlot', '~> 1.6'                    #图表

#pod 'ZBarSDK', '~> 1.3.1'                   #二维码扫描

#pod update --verbose --no-repo-update